setwd("//media//kswada//MyFiles//R//eqexp")

packages <- c("dplyr", "astsa", "tseries", "forecast", "MTS")
purrr::walk(packages, library, character.only = TRUE, warn.conflicts = FALSE)



# ------------------------------------------------------------------------------
# data:  eqexp
#   - Various bivariate earthquakes (EQ) and explosions (EX) recorded at 40 pts/s
#   - regional (100-2000km) recordings of several typical Scandinavian earthquakes and mining explosions measured by at seismic recording stations in Scandinavia
#   - 2 phases (P and S waves) or arrivals along the surface
#   - data are recorded at 40pts/s
#       - EQ:  earthquakes
#       - EX:  Explosions
#       - P waves:  Compressional waves, aka primary or P waves, travel fastest in the Earth's crust and are first to arrive
#       - S waves:  Shear waves propagate more slowly through the Earch and arrive second, called secondary or S waves
#
#   - General problem of interest is in distinguishing or discriminating between waveforms generated by earthquakes and those generated by explosions
# ------------------------------------------------------------------------------

data(eqexp, package = "astsa")


head(eqexp)

str(eqexp)



# ------------------------------------------------------------------------------
# basics
# ------------------------------------------------------------------------------

