setwd("//media//kswada//MyFiles//R//cafes")

packages <- c("dplyr", "rethinking")
purrr::walk(packages, library, character.only = TRUE, warn.conflicts = FALSE)



# ------------------------------------------------------------------------------
# data:  cafes  --> NOTE that data is generated by simulation at previous scripts
# ------------------------------------------------------------------------------


# ------------------------------------------------------------------------------
# Check prior for correlation matrix
# ------------------------------------------------------------------------------
# rlkjcorr() is function to compute density and produce random samples from the LKJ onion method correlation matrix distribution
# 

# What LKJcorr(2) distribution does is define a weakly informative prior on rho that is skeptical of extereme correlations near -1 or 1
# You can think of it as a regularizing prior for correlations.
# This distribution has a single paramter, eta, that controls how skeptical the prior is of large correlations in the matrix.
# When we use LKJcorr(1), the prior is flat over all valid correlation matrices.
# When the value is greater than 1, such as the 2, the extereme correlations are less likely.


# eta: parameter controlling shape of distribution
# K: dimension of correlation matrix

R1 <- rlkjcorr(1e4, K = 2, eta = 1)

R2 <- rlkjcorr(1e4, K = 2, eta = 2)

R4 <- rlkjcorr(1e4, K = 2, eta = 4)

str(R1)



# ----------
dens(R1[,1,2], xlab ="correlation", col = "black", ylim = c(0, 1.2))

dens(R2[,1,2], add = TRUE, col = "blue")

dens(R4[,1,2], add = TRUE, col = "red")


