setwd("//media//kswada//MyFiles//R//cafes")

packages <- c("dplyr", "rethinking")
purrr::walk(packages, library, character.only = TRUE, warn.conflicts = FALSE)



# ------------------------------------------------------------------------------
# data:  cafes  --> NOTE that data is generated by simulation at previous scripts
# ------------------------------------------------------------------------------


# ------------------------------------------------------------------------------
# model inspection
#  - posterior correlation between intercepts and slopes
# ------------------------------------------------------------------------------

post <- extract.samples(mod1)


# prior and posterior distribution
R2 <- rlkjcorr(6e3, K = 2, eta = 2)

dens(R2[,1,2], xlab ="correlation", col = "black", lty = 2, ylim = c(0, 2.5))

dens(post$Rho[,1,2], add=TRUE, col = "blue", lty = 1, lwd = 2)


# -->
# The posterior is concentrated on negative values, because the model has learned the negative correlation. (rho = -0.7)
# Keep in mind that the model did not get to see the true intercepts and slopes.
# All it had to work from was the observed wait times in morning and afternoon.

