setwd("//media//kswada//MyFiles//R//cafes")

packages <- c("dplyr", "rethinking")
purrr::walk(packages, library, character.only = TRUE, warn.conflicts = FALSE)



# ------------------------------------------------------------------------------
# data:  cafes  --> NOTE that data is generated by simulation at previous scripts
# ------------------------------------------------------------------------------

# ------------------------------------------------------------------------------
# Varying slopes model
# ------------------------------------------------------------------------------

mod1 <- map2stan(
  alist(
    wait ~ dnorm(mu, sigma),
    mu <- a_cafe[cafe] + b_cafe[cafe] * afternoon,
    c(a_cafe, b_cafe)[cafe] ~ dmvnorm2(c(a, b), sigma_cafe, Rho),
    a ~ dnorm(0, 10),
    b ~ dnorm(0, 10),
    sigma_cafe ~ dcauchy(0, 2),
    sigma ~ dcauchy(0, 2),
    Rho ~ dlkjcorr(2)
  ),
  data = d,
  iter = 5e3, warmup = 2e3, chains = 2, cores = 10
)


stancode(mod1)



# ----------
precis(mod1, digits=3, depth = 2)


