setwd("//media//kswada//MyFiles//R//cafes")

packages <- c("dplyr", "rethinking")
purrr::walk(packages, library, character.only = TRUE, warn.conflicts = FALSE)



# ------------------------------------------------------------------------------
# data:  cafes  --> NOTE that data is generated by simulation at previous scripts
# ------------------------------------------------------------------------------

# ------------------------------------------------------------------------------
# model inspection
#  - shrinkage (adaptive regularization)  --> plot the posterior mean varying effects
# ------------------------------------------------------------------------------

# compute unpooled estimates directly from data
a1 <- sapply(1:N_cafes, function(i) mean(wait[cafe_id == i & afternoon == 0]))

b1 <- sapply(1:N_cafes, function(i) mean(wait[cafe_id == i & afternoon == 1])) - a1




# ------------------------------------------------------------------------------
# extract posterior means of partially pooled estimates
# ------------------------------------------------------------------------------

post <- extract.samples(mod1)

a2 <- apply(post$a_cafe, 2, mean)

b2 <- apply(post$b_cafe, 2, mean)




# ------------------------------------------------------------------------------
# compute posterior mean bivariate Gaussian
# ------------------------------------------------------------------------------

Mu_est <- c(mean(post$a), mean(post$b))

rho_est <- mean(post$Rho[,1,2])

sa_est <- mean(post$sigma_cafe[,1])

sb_est <- mean(post$sigma_cafe[,2])

cov_ab <- sa_est * sb_est * rho_est

Sigma_est <- matrix(c(sa_est^2, cov_ab, cov_ab, sb_est^2), ncol = 2)




# ------------------------------------------------------------------------------
# convert varying effects to waiting times (oc: outcome)
# ------------------------------------------------------------------------------

wait_morning_1 <- (a1)

wait_afternoon_1 <- (a1 + b1)

wait_morning_2 <- (a2)

wait_afternoon_2 <- (a2 + b2)

Mu_est_oc <- c(mean(wait_morning_2), mean(wait_afternoon_2))

rho_est_oc <- cor(wait_morning_2, wait_afternoon_2)

sa_est_oc <- sd(wait_morning_2)

sb_est_oc <- sd(wait_afternoon_2)

cov_ab_oc <- sa_est_oc * sb_est_oc * rho_est_oc

Sigma_est_oc <- matrix(c(sa_est_oc^2, cov_ab_oc, cov_ab_oc, sb_est_oc^2), ncol = 2)



# ------------------------------------------------------------------------------
# Plot estimated intercepts and slopes, original data and estiamted values
# ------------------------------------------------------------------------------

par(mfrow=c(1,2))

library(ellipse)


# plot both and connect lines
plot(a1, b1, xlab = "intercept", ylab = "slope", pch = 16, col = rangi2, ylim = c(min(b1)-0.1, max(b1)+0.1), xlim=c(min(a1)-0.1, max(a1)+0.1))

points(a2, b2, pch = 1)

for(i in 1:N_cafes) lines(c(a1[i], a2[i]), c(b1[i], b2[i]))

for(l in c(0.1, 0.3, 0.5, 0.8, 0.99)) lines(ellipse(Sigma_est, centre=Mu_est, level=l), col=col.alpha("black", 0.2))



# -->
# blue points:  the unpooled estimates for each cafe
# open points: the posterior means from the varying effects model

# Notice the each open points is displaced from the blue towards the center of the contours, as a result of shrinkage in both dimensions
# Blue points farther from the center experience more shrinkage
# Notice too that shrinkage is not in direct lines towards the center.



# ----------
plot(wait_morning_1, wait_afternoon_1, xlab = "morning wait(mins)", ylab = "afternoon wait(mins)", pch = 16, col = rangi2, ylim = c(min(wait_afternoon_1)-0.1, max(wait_afternoon_1)+0.1), xlim=c(min(wait_morning_1)-0.1, max(wait_morning_1)+0.1))

points(wait_morning_2, wait_afternoon_2, pch = 1)

for(i in 1:N_cafes) lines(c(wait_morning_1[i], wait_morning_2[i]), c(wait_afternoon_1[i], wait_afternoon_2[i]))

for(l in c(0.1, 0.3, 0.5, 0.8, 0.99)) lines(ellipse(Sigma_est_oc, centre=Mu_est_oc, level=l), col=col.alpha("black", 0.2))

abline(0, 1, lty = 2)

# diagonal dashed line: where morning wait is equal to afternoon wait.
