setwd("//media//kswada//MyFiles//R//wish")

packages <- c("dplyr", "smacof")
purrr::walk(packages, library, character.only = TRUE, warn.conflicts = FALSE)



# ------------------------------------------------------------------------------
# data:  wish
# ------------------------------------------------------------------------------

data(wish, package = "smacof")


wish


car::some(wish)



# ------------------------------------------------------------------------------
# Compare exploratory MDS and confirmatory (circular) MDS
# ------------------------------------------------------------------------------

# method = max(wish):  integer value from which the similarity is subtracted
diss <- sim2diss(wish, method = max(wish))




# ----------
# Enforces a strict circle
res1 <- smacofSphere(diss, type = "ordinal")


# uses a penalty function that pushes the MDS solution in the direction of a perfect circle
# default penalty = 100 and when setting it to 22, say, the force that pulls the solution toward a perfect circle is mitigated.
# When setting the penalty weight to 100 (as default), then the circle is perfect, too.
res2 <- smacofSphere(diss, type = "ordinal", algorithm = "dual", penalty = 22)



# Exploratory MDS
res3 <- mds(diss, type = "ordinal")



# ----------
res1$stress

res2$stress 

res3$stress 




# ----------
op <- par(mfrow = c(1,3))

rownames(diss)

plot(res1, main="Circular MDS (primal)")

plot(res2, main="Circular MDS 2 (dual)")

plot(res3, main="Exploratory MDS")

par(op)



# -->
# As expected, the solution generated by the default algorithm has all country points on a perfect circle,
# while the solution computed by the dual algorithmn and using penalty = 22 only comes close to a perfect circle.

# The increment in Stress is not much high.
# The exporatory MDS solution is not that far from being circular:
# Only France (#5) and India (#6) needs to be pulled somewhat to the outside...

# When testing theories about real data, forcing the points onto a perfect circle in MDS space may seem exaggerated formalism,
# An approximate circle would be sufficient, but it is much harder to formulate this idea as a clear scaling target.
# Moreover, a perfect circle is, by itself, rarely ever a meaninfgul structural theory.
# It only becomes interesting if it is supplemented with additional notions such as a particular order of the points on the circle.
