setwd("//media//kswada//MyFiles//R//chicago")

packages <- c("dplyr", "lattice", "gamair")
purrr::walk(packages, library, character.only = TRUE, warn.conflicts = FALSE)


# This tutorial is based on
# Chapter 7. GAMs in Practive: mgcv from "Generalized Additive Models An Introduction with R 2nd Edition" (by Simon N. Wood)


# ------------------------------------------------------------------------------
# data:  chicago
#   - The data are from Peng and Wlty (2004)
#   - The response of interest is the daily death rate in Chicago, death, over a number of years.
#   - Possible explanatory variables for the observed death rate are
#        - levels of ozone (o3median)
#        - levels of sulpher dioxide (so2median)
#        - mean daily temperature (tmpd)
#        - levels of particulate matter (pm10median) (as generated by diesel exhaust, for example)
#   - In addition to these air quality variables, the underlying death rate tends to vary with time (in particular throughout the year)
# ------------------------------------------------------------------------------
data(chicago, package = "gamair")

str(chicago)



# ------------------------------------------------------------------------------
# basics statistics
# ------------------------------------------------------------------------------

par(mfrow = c(1,1))
plot(death ~ time, data = chicago, type = "h")


# -->
# clearly the number of deaths is cyclic and shows some outliers



# ----------
psych::describe(chicago)

hist(chicago$death)


